#!/usr/bin/env python3
"""Build rewards/icons.js from rewards/icons/*_color.svg (Microsoft Fluent Emoji Color, MIT: rewards/icons/LICENSE-fluentui-emoji.txt).
window.RW_ICONS = { name: "data:image/svg+xml;base64,..." }: one file that works in the app, the service worker and the offline
bundle (tools/bundle.py inlines scripts, not images). An <img> per data URI keeps each SVG's gradient ids to itself.
usage: python3 tools/rw_icons.py [--check]   (--check: exit 1 when rewards/icons.js is stale)"""
import base64
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "rewards", "icons")
OUT = os.path.join(ROOT, "rewards", "icons.js")


def text():
    names = sorted(f for f in os.listdir(SRC) if f.endswith("_color.svg"))
    rows = []
    for f in names:
        with open(os.path.join(SRC, f), "rb") as fh:
            rows.append('  "%s": "data:image/svg+xml;base64,%s"' % (f[:-len("_color.svg")], base64.b64encode(fh.read()).decode()))
    return ("/* rewards/icons.js: GENERATED by tools/rw_icons.py from rewards/icons/*_color.svg. Do not edit.\n"
            "   Microsoft Fluent Emoji Color, MIT License, Copyright (c) Microsoft Corporation (rewards/icons/LICENSE-fluentui-emoji.txt). */\n"
            "window.RW_ICONS = {\n" + ",\n".join(rows) + "\n};\n")


if __name__ == "__main__":
    t = text()
    if "--check" in sys.argv:
        sys.exit(0 if os.path.exists(OUT) and open(OUT, encoding="utf-8").read() == t else 1)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(t)
    print(OUT, len(t), "bytes")
